# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "any-serve"
version = "0.1.0"
edition = "2021"

[dependencies]

# TODO: Put only the used features
slint = { version = "1.2", default-features = true }

# TODO: Put only the used features
tokio = { version = "1.32", features = ["full"]}

# FTP server deps
libunftp = "0.18"
unftp-sbe-fs = "0.2"

# HTTP server deps: TODO: check whats needed
hyper = { version = "0.14", features = ["full"] }
tower-http = { version = "0.4", features = ["full"] }
tower = { version = "0.4", features = ["full"] }

# Log related
log = "0.4"
env_logger = "0.10"

# Required by the file dialog
rfd = "0.11"
async-trait = "0.1.73"
# async-trait = "0.1.73"

# For the headless version
# clap = "4.3"

[dev-dependencies]
tempfile = "3.8.0"
#ftp = "3.0.1"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true # Link time optimizations
panic = "abort" # Saves binary size on removing backtrace data on panic

