[package]
name = "any-serve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# chrono = { version = "0.4.26", default-features = false, features = ["clock", "std"] }

slint = { version = "1.1.1", default-features = true }

libunftp = "0.18.9"
tokio = "1.29.1"
