# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "any-serve"
version = "0.2.0"
edition = "2021"

[dependencies]

# TODO: Put only the used features
slint = { version = "1.2.2", default-features = true }

# TODO: Put only the used features
tokio = { version = "1.32.0", features = ["full"]}

# FTP server deps
libunftp = "0.19.0"
unftp-sbe-fs = "0.2.3"

# TFTP server
async-tftp = "0.3.6"

# HTTP server deps: TODO: check whats needed
hyper = { version = "0.14.27", features = ["full"] }
tower-http = { version = "0.4.4", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }

# Log related
log = "0.4.20"
env_logger = "0.10.0"

# Required by the file dialog
rfd = "0.12.0"
async-trait = "0.1.73"

# For the headless version
# clap = "4.3"

[dev-dependencies]
tempfile = "3.8.0"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true # Link time optimizations
panic = "abort" # Saves binary size on removing backtrace data on panic

