# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "any-serve"
version = "0.1.0"
edition = "2021"

[dependencies]

# TODO: Put only the used features
slint = { version = "1.1", default-features = true }

# TODO: Put only the used features
tokio = { version = "1.29", features = ["full"]}

libunftp = "0.18"
unftp-sbe-fs = "0.2"

tracing-subscriber = "0.3"
tracing = "0.1"

# clap = "4.3"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true # Link time optimizations
panic = "abort" # Saves binary size on removing backtrace data on panic
