# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
authors =  ["João Loureiro"]
name = "any-serve"
version = "0.2.1"
edition = "2021"

[dependencies]
# TODO: Put only the used features
tokio = { version = "1.35.1", features = ["full"]}
futures = "0.3.30"
async-trait = "0.1.75"

# FTP server deps
libunftp = "0.19.1"
unftp-sbe-fs = "0.2.4"

# TFTP server
async-tftp = "0.3.6"

# HTTP server deps: TODO: check whats needed
hyper = { version = "0.14.28", features = ["full"] }
tower-http = { version = "0.4.4", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }

# Log related
log = "0.4.20"
env_logger = "0.10.1"

# For the headless version
clap = { version = "4.4.11", features = ["derive"] }
ctrlc = "3.4.2"

[dev-dependencies]
tempfile = "3.8.1"
assert_cmd = "2.0.12"
predicates = "3.0.4"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true # Link time optimizations
panic = "abort" # Saves binary size on removing backtrace data on panic

