name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule:
  #   - cron: '0 0 * * *'

env:
  CARGO_TERM_COLOR: always
  TARGETS: "x86_64-pc-windows-gnu x86_64-unknown-linux-gnu armv7-unknown-linux-gnueabihf aarch64-unknown-linux-gnu"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    ##################################
    # - name: Cache Rust dependencies
    #   uses: actions/cache@v2
    #   with:
    #     path: |
    #       ~/.cargo/registry
    #       ~/.cargo/git
    #       target

    ###################################
    - name: Setup for Linux x86_64
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install build dependencies
      run: |
          sudo apt install libgtk-3-dev libatk1.0-dev
          rustup target add $TARGETS

    - name: Build for Linux x86_64
      continue-on-error: false
      run: cargo build --release

    # ################################### 
    # - name: Set up Rust for ARM
    #   uses: actions-rs/toolchain@v1
    #   with:
    #     profile: minimal
    #     toolchain: stable-armv7-unknown-linux-gnueabihf

    # - name: Build for ARM
    #   run: cargo build --release --target=armv7-unknown-linux-gnueabihf

    # ################################### 
    # - name: Set up Rust for Windows
    #   uses: actions-rs/toolchain@v1
    #   with:
    #     profile: minimal
    #     toolchain: stable-x86_64-pc-windows-msvc

    # - name: Build for Windows
    #   run: cargo build --release --target=x86_64-pc-windows-msvc